# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.8.4-base

# build-time tokens for gated downloads — never baked into final image.
# pass via: docker build --build-arg HF_TOKEN=$HF_TOKEN ...
ARG HF_TOKEN=""

# install custom nodes into comfyui
RUN git clone https://github.com/nkxx188/ComfyUI-MiniMaxH3-Easy /comfyui/custom_nodes/ComfyUI-MiniMaxH3-Easy && cd /comfyui/custom_nodes/ComfyUI-MiniMaxH3-Easy && (git checkout 0b23d8783bf98d72e9778fd70541b0846770b5f3 2>/dev/null || (git fetch origin 0b23d8783bf98d72e9778fd70541b0846770b5f3 --depth=1 && git checkout 0b23d8783bf98d72e9778fd70541b0846770b5f3) || echo "WARN: commit 0b23d8783bf98d72e9778fd70541b0846770b5f3 unreachable in https://github.com/nkxx188/ComfyUI-MiniMaxH3-Easy, falling back to default branch HEAD")
RUN git clone https://github.com/Larryvrh/ComfyUI-MiniMax-H3-Turbo /comfyui/custom_nodes/ComfyUI-MiniMax-H3-Turbo && cd /comfyui/custom_nodes/ComfyUI-MiniMax-H3-Turbo && (git checkout 96cc1ddc001617da132dd73f31cd43666bf1d8d4 2>/dev/null || (git fetch origin 96cc1ddc001617da132dd73f31cd43666bf1d8d4 --depth=1 && git checkout 96cc1ddc001617da132dd73f31cd43666bf1d8d4) || echo "WARN: commit 96cc1ddc001617da132dd73f31cd43666bf1d8d4 unreachable in https://github.com/Larryvrh/ComfyUI-MiniMax-H3-Turbo, falling back to default branch HEAD")
RUN git clone https://github.com/xmarre/ComfyUI-Spectrum-MiniMax-H3 /comfyui/custom_nodes/ComfyUI-Spectrum-MiniMax-H3 && cd /comfyui/custom_nodes/ComfyUI-Spectrum-MiniMax-H3 && (git checkout dc6e1b335e1cdcd078a649add6464dab9469a587 2>/dev/null || (git fetch origin dc6e1b335e1cdcd078a649add6464dab9469a587 --depth=1 && git checkout dc6e1b335e1cdcd078a649add6464dab9469a587) || echo "WARN: commit dc6e1b335e1cdcd078a649add6464dab9469a587 unreachable in https://github.com/xmarre/ComfyUI-Spectrum-MiniMax-H3, falling back to default branch HEAD")
RUN comfy node install --exit-on-fail comfyui-kjnodes@1.4.7 --mode remote || (echo "WARN: comfyui-kjnodes@1.4.7 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-kjnodes --mode remote)
RUN git clone https://github.com/kijai/ComfyUI-SolAttn_triton /comfyui/custom_nodes/ComfyUI-SolAttn_triton

# download models into comfyui
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/diffusion_models/minimax_h3_fl2va_pruned_int8_convrot.safetensors' --relative-path models/Unknown --filename 'minimax_h3_fl2va_pruned_int8_convrot.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/taurusduan/MiniMax-H3/resolve/main/diffusion_models/minimax_h3_ref2va_pruned_int8_convrot.safetensors' --relative-path models/Unknown --filename 'minimax_h3_ref2va_pruned_int8_convrot.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors' --relative-path models/Unknown --filename 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/minimax_h3_video_vae_fp16.safetensors' --relative-path models/Unknown --filename 'minimax_h3_video_vae_fp16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/minimax_h3_audio_vae_fp32.safetensors' --relative-path models/Unknown --filename 'minimax_h3_audio_vae_fp32.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/larryvrh/MiniMax-H3-Turbo-Lora/resolve/main/minimax_h3_turbo_4step_ema_ckpt850.safetensors' --relative-path models/Unknown --filename 'minimax_h3_turbo_4step_ema_ckpt850.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
